version: '3.8'

services:
  web:
    build: .
    container_name: taskmanager_web
    ports:
      - "80:80"
    volumes:
      - ./src:/var/www/html
    networks:
      - taskmanager-network
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: taskmanager_db
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: task_manager
      MYSQL_USER: user
      MYSQL_PASSWORD: userpass
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - taskmanager-network

networks:
  taskmanager-network:
    driver: bridge

volumes:
  db_data:
